services:
  - type: web
    name: enigma-api
    runtime: docker
    plan: free
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: NVIDIA_API_KEY
        sync: false
      - key: NVIDIA_BASE_URL
        sync: false
      - key: AI_MODEL
        sync: false
      - key: AI_PROVIDER
        sync: false
      - key: SECRET_KEY
        generateValue: true
